### ISSUE TITLE
Handle TVDB errors better

### ISSUE THREAD

**Issue by adhawkins** [dbr/tvnamer#102]
Hi,

When tvnamer fails to download data from the TVDB, it still goes on to suggest renaming a file (typically offering to remove any 'name' part).

e.g.

```
####################
# Processing file: Casualty - s29e11 - Asylum.mkv
# Detected series: Casualty (season: 29, episode: 11)
DataRetrievalError('Error with www.thetvdb.com: Could not connect to server: HTTP Error 522: Origin Connection Time-out',)
####################
Old filename: Casualty - s29e11 - Asylum.mkv
Before custom output replacements: Casualty - s29e11.mkv
New filename: Casualty - s29e11.mkv
Rename?
([y]/n/a/q)
```

Here's it's offering to rename a correctly named file by removing the episode title.

It would be better if it either retried the attempt, or displayed an error and didn't offer to rename.

**Comment by rustymyers** [comment]
I agree that there could be better handling of tvdb connection errors, I experienced long delays while trying to retrieve information. However, I prefer some files to be renamed and have the title removed, as sometimes it's incorrect. This is why I suggest it be a preference (in fact it may already be, I'm not sure: https://github.com/dbr/tvnamer/blob/master/tvnamer/config_defaults.py). Thanks.

**Comment by dbr** [comment]
I think having the `skip_file_on_error` apply interactively makes sense, maybe preserving the current true/false behaviour, and introduce:

```
skip_file_on_error: "always" # skip file interactively and in batch
skip_file_on_error: "batch" # skip file in batch mode, prompt interactively
skip_file_on_error: "never" # always rename
```

**Comment by rustymyers** [comment]
I agree, those sound like appropriate options.

**Comment by dbr** [comment]
Closing old issue; solved by `skip_file_on_error`/`skip_behaviour` options from #111
