### ISSUE TITLE
How to ignore words?

### ISSUE THREAD

**Issue by Crowley1997** [dbr/tvnamer#104]
Is there a way to ignore a word from the file name?
For example:
google.com_the100.1x1.avi
How do i tell the program to ignore the "google.com"?

**Comment by lahwaacz** [comment]
Adjust the regex in the [filename_patterns](https://github.com/dbr/tvnamer/blob/master/tvnamer/config_defaults.py#L143) list in your config.

**Comment by Crowley1997** [comment]
I didn't get it. :/
Can you explain?

**Comment by dbr** [comment]
It would be much easier to use the `input_filename_replacements` config option, e.g:

```json
{
    "input_filename_replacements": [
        {"is_regex": false,
        "match": "google.com",
        "replacement": ""}
    ]
}
```

There are more examples in https://github.com/dbr/tvnamer/blob/master/tests/test_custom_replacement.py

**Comment by Crowley1997** [comment]
Thanks, It worked!
