### ISSUE TITLE
Multiple move files destinations

### ISSUE THREAD

**Issue by zakphi** [dbr/tvnamer#107]
I have two folders that contain tv shows, one folder contains shows that i watch alone and the other is shows that I watch with my fiance. is there a way we can create multiple destinations and then have an option after renaming the file that will allow us to choose where to move the file?

essentially it would run like this:
run script on video file
choose search results from list
confirm new filename
choose new destination
etc.

**Comment by lozbrown** [comment]
You could create two different config files with different paths and then run them slightly seperately

tvnamer --config=/home/zakphi/programsforme.json Filthy.dirty.honeys.S01E02.mkv
tvnamer --config=/home/zakphi/programsforbothofus.json Soppy.romcom.S01E02.mkv

you could even create aliases for these makeing calling them easier

**Comment by zakphi** [comment]
thanks for the help. now i just gotta figure out how the moving of files work
