### ISSUE TITLE
File gets renamed but not moved

### ISSUE THREAD

**Issue by houdini3009** [dbr/tvnamer#115]
My files are getting renamed properly but do not get moved. How can I discover why? It seems like my setting for "move_files_destination" is being totally ignored. Here's my JSON config. Am I doing something wrong??

{
    "always_move": true,
    "always_rename": true,
    "filename_anime_with_episode": "S%(seasonnumber)02dE%(episode)s - %(episodename)s%(ext)s",
    "filename_anime_with_episode_without_crc": "S%(seasonnumber)02dE%(episode)s - %(episodename)s%(ext)s",
    "filename_anime_without_episode": "S%(seasonnumber)02dE%(episode)s%(ext)s",
    "filename_anime_without_episode_without_crc": "S%(seasonnumber)02dE%(episode)s%(ext)s",
    "filename_with_date_and_episode": "S%(seasonnumber)02dE%(episode)s - %(episodename)s%(ext)s",
    "filename_with_date_without_episode": "S%(seasonnumber)02dE%(episode)s%(ext)s",
    "filename_with_episode": "S%(seasonnumber)02dE%(episode)s - %(episodename)s%(ext)s",
    "filename_with_episode_no_season": "S%(seasonnumber)02dE%(episode)s - %(episodename)s%(ext)s",
    "filename_without_episode": "S%(seasonnumber)02dE%(episode)s%(ext)s",
    "filename_without_episode_no_season": "S%(seasonnumber)02dE%(episode)s - %(episodename)s%(ext)s",
    "move_files_enabled": true,
    "move_files_confirmation": false,
    "move_files_destination": "/Volumes/video/TV/"
}

**Comment by houdini3009** [comment]
RESOLVED. Apparently even when you set "always_move" to true, you still need to pass the "--move" option when executing tvnamer.

**Comment by dbr** [comment]
Yeh, that option is a bit confusingly named - `always_move` auto-accepts the "move this file?" prompt, but the feature is not enabled by default. I think instead you are looking for `move_files_enable`
