### ISSUE TITLE
Feature Req - ability to blacklist specific series

### ISSUE THREAD

**Issue by jedd** [dbr/tvnamer#135]
Greetings,

Would it be possible to have a configuration to exclude a specific set of series-ID's from thetvdb lookup?

For example tvnamer typically shows 'The Simpsons' and 'Jessica Simpson' whenever it sees the word 'Simpson' in a filename.

Obviously normal people will never have one of those files on their computer, and it'd be great to be able to avoid the 'Enter choice' prompt.

**Comment by dbr** [comment]
I believe this could be done with the `input_series_replacements` option? Either replacing "Simpsons" with "The Simpsons", or with the specific series ID

There is example configs for both these approaches in the test cases:
https://github.com/dbr/tvnamer/blob/master/tests/test_series_replacement.py#L11

E.g
```json
{
    "input_series_replacements": {
        "seriesnamegoeshere": 76156}
}
```

**Comment by jedd** [comment]
Oh, fantastic, thank you.  I did look through for some blacklist options,
didn't think to check replacements as a way of excluding across the board.

 Have tested - works well.

 Thank you again!
