### ISSUE TITLE
TVDB API v2 update plans

### ISSUE THREAD

**Issue by JohnKacz** [dbr/tvnamer#138]
I made this comment [here](https://github.com/dbr/tvnamer/issues/137#issuecomment-304085019) but thought I'd make a separate issue to ask this question.

Are there plans for tvnamer to start using the v2 API. I had this error as well and read that

> This version of the API will continue to function until October 1st, 2017 at which time it will be discontinued

**Comment by frederickjh** [comment]
I too am interested to know if if there are plans to update this script to switch from the current V1 XML format to the V2 JSON format.  The programer's API page currently looks like this.

![image](https://user-images.githubusercontent.com/864159/28817264-ee36fa56-76a7-11e7-9a66-f6fe5e1da688.png)

The [new V2 API](http://www.thetvdb.com/wiki/index.php?title=Programmers_API) was made public on[ 20:07, 25 April 2016 by Coco](http://www.thetvdb.com/wiki/index.php?title=Programmers_API&direction=next&oldid=903). The end date of October 1st, 2017 was made public on [22:49, 2 April 2017](http://www.thetvdb.com/wiki/index.php?title=Programmers_API&direction=next&oldid=931). 

This means that only 6 months notice was given that they old API will be discontinued and that there are now only 3 months left before it will be turned off.

[The TVDB REST API (v2.1.2) Documentation](https://api.thetvdb.com/swagger)

**Comment by Deathnerd** [comment]
I'd also like to throw my hat into the ring for a shift to the v2 API if extra hands are needed

**Comment by dbr** [comment]
Oh, good point - there is some changes pending a bit more testing in dbr/tvdb_api#58
which should address this for tvnamer also

**Comment by Deathnerd** [comment]
So... No hands needed yet?

**Comment by rustymyers** [comment]
Seems like the work needs done on the tvdb_api https://github.com/dbr/tvdb_api/issues/57

**Comment by freedenizen** [comment]
Looks dbr/tvdb_api#57 and dbr/tvdb_api#58 have been closed.

**Comment by JohnKacz** [comment]
Yes seems changes were actually merged in https://github.com/dbr/tvdb_api/pull/60
