### ISSUE TITLE
call from a script in spyder

### ISSUE THREAD

**Issue by daviddoji** [dbr/tvnamer#139]
First of all, thank you for this wonderful script man!

I'm trying to get it running from another script I'm writing to organize subtitles of different languages. The idea is to call it from a script within Spyder IDE:
```
do some other stuff
tvnamer .
continue doing stuff
```
When I try to use it, I get a 
```
    tvnamer .
             ^
SyntaxError: invalid syntax
```

How can I do it?

Thanks in advance.

**Comment by rustymyers** [comment]
try calling it with python?

`python tvnamer .`

**Comment by dbr** [comment]
If you are calling tvnamer from a Python script, you would either need to use something like the subprocess module to run the `tvnamer` command like you would from a terminal
https://docs.python.org/2/library/subprocess.html

Something like

```python
import subprocess
args = ["tvnamer", "--batch", "."]
subprocess.call(args)
```
