### ISSUE TITLE
H.264 in filename incorrectly interpreted as season 2, episode 64

### ISSUE THREAD

**Issue by antgel** [dbr/tvnamer#140]
```# Processing file: Connections - 10 - Yesterday, Tomorrow and You - H.264.m4v
# Detected series: Connections - 10 - Yesterday, Tomorrow and You - H (season: 2, episode: 64)
ShowNotFound(u'Show Connections - 10 - Yesterday, Tomorrow and You - H not found on www.thetvdb.com',)
####################
Old filename: Connections - 10 - Yesterday, Tomorrow and You - H.264.m4v
New filename: Connections - 10 - Yesterday, Tomorrow and You - H - [02x64].m4v
```

**Comment by dbr** [comment]
There is a filename pattern to handle `show.123.avi` as season 1, episode 23 - I'm tempted to remove this from the default patterns as it is very ambiguous, like in this case

In this case you'd have to add a custom pattern to handle that filename, as filenames with no season number aren't handled (once "fixed", that file will just be skipped over with a `Invalid filename: Cannot parse ...` warning)

**Comment by antgel** [comment]
Thank you for this!
