### ISSUE TITLE
main.py is not included in PyPI release

### ISSUE THREAD

**Issue by sandrotosi** [dbr/tvnamer#147]
main.py file is missing from pypi release, ie tvnamer is unusable if installed from there

**Comment by dbr** [comment]
Strange - could you test the newly made 2.5 release? Seems to work for me:

```
$ mkvirtualenv tvn25test
...
$ pip install tvnamer==2.5
...
$ tvnamer --help
Usage: tvnamer [options] <files>

Options:
...
```

**Comment by dbr** [comment]
Shall close this for now; reopen if this is still an issue

**Comment by sandrotosi** [comment]
if you didnt update MANIFEST.in to include main.py then yes, this is still an issue (we are using 2.5 already)

**Comment by dbr** [comment]
Hmm, the manifest doesn't contain main.py but the Python source files should be included by default:

```
$ tar tf tvnamer-2.5.tar.gz  | grep main
tvnamer-2.5/tvnamer/main.py
```

Can you give more details on what troubles this is causing? The files seem present in the archive and it installs successfully via pip as far as I can tell

**Comment by dbr** [comment]
Ohh, just realised you are probably referring to the top-level `main.py`,
https://github.com/dbr/tvnamer/blob/master/main.py

I forgot that still existed! I'm kind of tempted to remove this as it's mostly a legacy of the old structure of the code, which was left there was the unittests use it

How are you using `main.py`? Is there some other approach which would work for this? (I'm thinking of allowing `python -m tvnamer ...` to work as that seems more conventional these days, e.g `python -m venv`)

**Comment by dbr** [comment]
In latest master, the top-level main.py has been removed and in it's place you can do `python -m tvnamer` if the entrypoint script is unsuitable for whatever reason
