### ISSUE TITLE
Change default show

### ISSUE THREAD

**Issue by kdog0598** [dbr/tvnamer#156]
I was wondering if there was a way to change the default, number 1 result that appears for a show? For example, Mr. Robot lists "Mr. Robot Digital After Show" first which throws a wrench into my automated renaming. Is there an option I can set somewhere for certain shows like this?

**Comment by dbr** [comment]
Yep! The `input_series_replacements` config option can do that - you can replace a given string with another, or, map a string to a given TVDB ID

https://github.com/dbr/tvnamer/blob/f5a9060be8f78f45f023fb65d4d9d5dd2fef9ae6/tvnamer/config_defaults.py#L451-L454

and there are some examples here:

https://github.com/dbr/tvnamer/blob/f5a9060be8f78f45f023fb65d4d9d5dd2fef9ae6/tests/test_series_replacement.py#L38-L43

You can find the series ID on the shows page, e.g on
https://www.thetvdb.com/series/mr-robot
"TheTVDB.com Series ID" is `289590`

**Comment by kdog0598** [comment]
Thank you very much! I had found this answer in another issue but forgot to close this one. Then TVDB's api stopped working so I hadn't had the chance to try it.

**Comment by msw1970** [comment]
Is it possible to use wildcards within the input_series_replacements section such as..

Marvel*s Agents of S*

**Comment by kdog0598** [comment]
Yeah you can. For mine I used {“Mr* Robot”: ###} because the period was disappearing.

**Comment by msw1970** [comment]
Many thanks.. This has indeed helped, however, I do note that all of the shows now failing without this were working successfully a week ago before the changes at TVDB

**Comment by kdog0598** [comment]
Yeah it’s the same on my end. At least tvdb’s api is working at all now.
