### ISSUE TITLE
Matching Issues With New TVDB API

### ISSUE THREAD

**Issue by msw1970** [dbr/tvnamer#162]
Hi 

So, tvnamer, seems to be "working" again after the issues with thetvdb api over the last few days, however, I'm now finding an increasing number of shows "mis-matching" when using a config file (effectively running in batch mode) and therefore being incorrectly renamed or failing on the series "not existing". Examples include...

The Blacklist - Selecting The Blacklist: Redemption
Marvel's Agents of SHIELD - Selecting Marvel's Agents of S.H.I.E.L.D.: Academy
Watchmen - Selecting Watchmen: Motion Comic
Mr Robot - Selecting Mr Robot Digital

There's then a number of shows where no match is being found although when I search on thetvdb website the show appears

Silicon Valley
The Path

Is there anything that I can do within the config file to enforce exact matching only until this is properly fixed as it's breaking some of my home automation tasks.

**Comment by emeidi** [comment]
Certain series constantly get identified wrongly; I therefore use the following switch to "pin" the ID based on the name of the folder my script is operating on (yes, this is hardcoded in my master script):

`tvnamer ... --series-id 281618`

**Comment by dbr** [comment]
In addition to the command line arg, #156 has details on how to do this via the config too

**Comment by CWSpear** [comment]
The stuff in #156 helps, but can we get a way of preferring more exact matches? There seems to be a lot of these occurrences, and it's a major pain. :(
