### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by jxp05j** [dbr/tvnamer#163]
I am getting this error any time I try to use tvnamer:

`Traceback (most recent call last):
  File "/usr/local/Cellar/tvnamer/2.5/libexec/bin/tvnamer", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'`

This happens even when I just try to load the help, so I don't think it is related to the tvdb issues.  I have uninstalled and reinstalled with homebrew several times, and I always get the same error.  I am running 2.5.  Thanks for any guidance you can give!

**Comment by dbr** [comment]
Not to do with tvnamer, I think your Python install is missing setuptools,

    pip install setuptools

Should fix it as according to https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
