### ISSUE TITLE
Please support Movie rename too

### ISSUE THREAD

**Issue by Monirzadeh** [dbr/tvnamer#176]
is it possible to add movie rename feature to tvnamer?
what do you need for that?

**Comment by dbr** [comment]
While possible, this isn't something I would want to add to tvnamer.

I think this would add to much additional complexity into tvnamer (not much of hte code would be shared between the two, so would likely be better as a separate tool), and so would prefer to keep it focused on just renaming TV episodes!

**Comment by dbr** [comment]
There are some other projects which handle both - https://github.com/jkwill87/mnamer seems like a quite well maintained one currently. There is also various non-Python based tools like Radarr and FileBotf
