### ISSUE TITLE
Ever thought about a GUI?

### ISSUE THREAD

**Issue by gnacho** [dbr/tvnamer#192]
This was a great project, but seems to be dead: https://gitlab.com/mmstick/tv-renamer

Tvnamer coming with a GUI, for non-advanced user would be great.

**Comment by dbr** [comment]
I've thought about it (and even started on one [a very long time ago](https://github.com/dbr/tvnamergui_osx)), however this isn't something I'd personally want to make and maintain these days (I don't even use tvnamer myself much currently!)

I am hoping to make the internals of tvnamer easier to access with version 4 - so in theory someone could write a GUI using the core of tvnamer

I would recommend maybe looking into something like [Sonarr](https://sonarr.tv/) - although slightly more complex to setup than something like tv-renamer, it does have a nice UI around manually adding files and batch renaming (even if you don't use the automatic downloading functionality)
