### ISSUE TITLE
Issue with UK version of 'The Office'

### ISSUE THREAD

**Issue by adhawkins** [dbr/tvnamer#206]
If I name the files:

```The Office (UK) - s01e01.mkv```

if wants to rename to 

```The Office - s01e01 - Downsize.mkv```

(fair enough)

However, next time I run tvnamer, it wants to rename the same file to:

```The Office (US) - s01e01 - Pilot.mkv```

It does this for all episodes in all seasons (including specials)

**Comment by dbr** [comment]
There's not much that can be done to fix this in general sense, as it's just TheTVDB's search returns the US series first (even if the search term is an 100% match to the non-US series) :shrug:

However you fix it in an ad-hoc manner by remapping "The Office" to the correct series ID, like this example config:

https://github.com/dbr/tvnamer/blob/2e1e969542d65c5cac2dad9b3cd20dce4f53b6a8/tests/test_series_replacement.py#L38-L43

You can find the appropriate series ID either in tvnamer's interactive prompt, or on TheTVDB website, e.g https://thetvdb.com/series/the-office "TheTVDB.com Series ID 78107"

**Comment by adhawkins** [comment]
Great, thanks. Will give that a try and report back.

**Comment by adhawkins** [comment]
That's perfect, works a treat. Thanks a lot for the assistance.
