### ISSUE TITLE
Is there an easy way to generate filenames with not white spaces?

### ISSUE THREAD

**Issue by alienbogart** [dbr/tvnamer#209]
Title.

**Comment by dbr** [comment]
Simplest way is to add a space into the `custom_filename_character_blacklist` option, which will replace them with the character specified in `replace_invalid_characters_with` (default is `_`)

https://github.com/dbr/tvnamer/blob/3.0.4/tvnamer/config_defaults.py#L79-L82

You can also use the `output_filename_replacements` to do more specific replacements:
https://github.com/dbr/tvnamer/blob/3.0.4/tests/test_custom_replacement.py#L109-L117
