### ISSUE TITLE
Support for DVD order

### ISSUE THREAD

**Issue by tremby** [dbr/tvnamer#23]
I haven't had a good look through tvdb yet but my very first thought on finding tvnamer was which order exactly will it put the episodes in -- original airing order or creator's intended order? I found a page about it on the tvdb wiki: http://www.thetvdb.com/wiki/index.php/DVD_Order

Is there any support for this? I'd always like to be my episodes to use the season numbers/episode numbers the creator intended, not what the network ended up using.

**Comment by clee** [comment]
Any updates on this? Does `tvdb_api` support it yet?

**Comment by dbr** [comment]
Oh, yes, this has been implemented - there is the `order` config option to switch from default of `aired` to `dvd, e.g:

```json
{"order": "dvd"}
```

**Comment by dbr** [comment]
(or `tvnamer --order dvd ...`)

**Comment by dbr** [comment]
From PR #105
