### ISSUE TITLE
Option to use symlinks

### ISSUE THREAD

**Issue by mb5** [dbr/tvnamer#46]
It would be nice to use symlink instead of moving/renaming the original file so that applications can still access the file from its previous location. I would suggest two options: link-to to generate a link to the original file with the new name at the new location and link-from to generate a link with the old name after the file has been moved/renamed.

**Comment by f4hy** [comment]
Looks like your pull request implemented link-from, but the link-to option this issue requested appears to still be unimplemented.

**Comment by tremby** [comment]
Yup, fair enough.

**Comment by dbr** [comment]
Closing old ticket - will be implemented via #190
