### ISSUE TITLE
When querying the tvdb returns an error, exit with an appropriate error code

### ISSUE THREAD

**Issue by mb5** [dbr/tvnamer#73]
Currently, tvnamer exits with 0 even though renaming failed if say tvdb should return a 4xx or 5xx HTTP error. Especially the later ones usually indicate server errors. This behavior makes it more difficult to use tvnamer in scripts if one needs to detect failures.
tvnamer should therefore exit with an appropriate error code if renaming should fail because of any HTTP errors.

**Comment by dbr** [comment]
`skip_behaviour` config option now controls this
