### ISSUE TITLE
Force overwrite when proper/repack

### ISSUE THREAD

**Issue by nohatssir** [dbr/tvnamer#84]
Hey!

I've set up a script (runs as a cronjob) that goes through all files in a directory with tvnamer which then moves them to another specific directory. 

I first get an episode of any show and let tvnamer move it. After a while a proper/repack version of the same episode is downloaded and renamed. But it won't get moved since there's already a file with the same name.

Is there a way you could implement a check for keywords as proper or repack and then force an overwrite automatically (or is this maybe already possible)?

**Comment by lozbrown** [comment]
I'm not sure why this was closed but this still seems a very valid and useful addition

Something along the lines of 
IF (Config['overwrite_destination_on_repack_proper'] AND (re.I.search['proper',fullpath] or re.I.search['repack',fullpath])) or Config['overwrite_destination'] 

the force= true
